### ISSUE TITLE
Error "undefined method `render' for main:Object"

### ISSUE THREAD

**Issue by tordans** [Locale/locale_flash#7]
We used the example code for the initializer inside our Rail 5.0 app which results in an error 
```
undefined method `render' for main:Object
```
Did anyone work around this already?

**Comment by tjouan** [comment]
Thank you for the report!

I confirm I get an error too, slightly different message but I guess
it's the same error.

We're looking into the issue, I'll let you know when we find a fix.

**Comment by tjouan** [comment]
I think it's just a documentation error, and not a problem in the gem
behavior. We can assign any proc to `LocaleFlash::Config.template`,
and as far as I can tell it's called properly.

The documentation suggests an "initializer" with an example of proc
where `self` is `main`, which is an `Object` and do not implement
`#render`. If the proc was defined in the context of a controller
instance, in an action, it would work as expected, we could call the
well-known `#render` method.

I think the example should not depend too much on rails to be more
correct:

``` ruby
LocaleFlash::Config.template = -> type, str do
  "<p class=#{type}>#{str}</p>"
end
```

Now if do want to render a view in rails5, it seems "render" method is
also available on controller classes as
`ApplicationController.render`, so we could set the template this way:
``` ruby
LocaleFlash::Config.template = -> type, str do
  ApplicationController.render(
    template: 'application/flash',
    locals: {
      type: type,
      str:  str
    }
  )
end
```

**Comment by ghost** [comment]
I believe our change to the documentation:
https://github.com/Locale/locale_flash/pull/8
fixes this issue, so I'm closing.

Thank you for reporting it!

**Comment by tordans** [comment]
Thanks for the help.

The example code above worked for me with small changes (`partial:` instead of `template`).
The example from the new readme works as well but does not feed ideal since one has the html in an initialiser.

```
# /config/initializers/locale_flash.rb
LocaleFlash::Config.template = -> type, str do
  ApplicationController.render(
    partial: 'layouts/flash',
    locals: {
      type: type,
      str:  str
    }
  )
end
```

Our bootstrap4 code looks like this:
```
# /app/views/layouts/_flash.html.slim
- bootstrap_types = { 'notice' => 'success', 'alert' => 'danger' }
.container
  .row
    .col-md-12
      .alert class="alert-#{bootstrap_types[type]}" role='alert'
        = str
```

**Comment by ghost** [comment]
> The example code above worked for me with small changes (`partial:` instead of `template`).

Yes I think it depends how your view (or partial here) is named:
"app/views/layouts/_flash.html.slim"
vs:
"app/views/layouts/flash.html.slim"
for example

> The example from the new readme works as well but does not feed ideal since one has the html in an initialiser.

Yes I agree, it was meant to simplify the example and just rely on a string, and show that we could return HTML if we wanted to.
The problem with a more complex example is that it can be incorrect more easily, and if we rely on parts of Rails API we may have to maintain it, or show different examples for different versions, different templating libraries etc…

Let me know if you have suggestions to improve it (here or with a PR), ideally it should stay simple.

Another solution could be to just add a link to the correct rails guide/doc about view rendering if we fill this is what's missing from our doc.
